//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperVTray.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HyperVTray.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Virtual Machines.
        /// </summary>
        internal static string Menu_AllVirtualMachines {
            get {
                return ResourceManager.GetString("Menu_AllVirtualMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyper-V could not be found on this machine, or it is not running. Please ensure that the Hyper-V role has been enabled and that Hyper-V is running..
        /// </summary>
        internal static string Message_HyperVNotFound {
            get {
                return ResourceManager.GetString("Message_HyperVNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to manage Hyper-V. Please ensure you are a member of the &quot;Hyper-V Administrators&quot; group, or run the application again as administrator..
        /// </summary>
        internal static string Message_NoHyperVPermission {
            get {
                return ResourceManager.GetString("Message_NoHyperVPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to launch Hyper-V Manager..
        /// </summary>
        internal static string Message_OpenHyperVManagerFailed {
            get {
                return ResourceManager.GetString("Message_OpenHyperVManagerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string State_Off {
            get {
                return ResourceManager.GetString("State_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string State_Paused {
            get {
                return ResourceManager.GetString("State_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string State_Running {
            get {
                return ResourceManager.GetString("State_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string State_Saved {
            get {
                return ResourceManager.GetString("State_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string State_Unknown {
            get {
                return ResourceManager.GetString("State_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Virtual Machine.
        /// </summary>
        internal static string String_UnknownVirtualMachine {
            get {
                return ResourceManager.GetString("String_UnknownVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyper-V Not Running.
        /// </summary>
        internal static string Title_HyperVNotFound {
            get {
                return ResourceManager.GetString("Title_HyperVNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyper-V Permission Error.
        /// </summary>
        internal static string Title_NoHyperVPermission {
            get {
                return ResourceManager.GetString("Title_NoHyperVPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine is in a critical state..
        /// </summary>
        internal static string Toast_CriticalState {
            get {
                return ResourceManager.GetString("Toast_CriticalState", resourceCulture);
            }
        }
    }
}
