//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperVTray.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsFallback {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsFallback() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HyperVTray.Resources.StringsFallback", typeof(StringsFallback).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do&amp;n&apos;t Reset.
        /// </summary>
        internal static string Button_DontReset {
            get {
                return ResourceManager.GetString("Button_DontReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do&amp;n&apos;t Shut Down.
        /// </summary>
        internal static string Button_DontShutDown {
            get {
                return ResourceManager.GetString("Button_DontShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do&amp;n&apos;t Turn Off.
        /// </summary>
        internal static string Button_DontTurnOff {
            get {
                return ResourceManager.GetString("Button_DontTurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        internal static string Button_Reset {
            get {
                return ResourceManager.GetString("Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Shut Down.
        /// </summary>
        internal static string Button_ShutDown {
            get {
                return ResourceManager.GetString("Button_ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Turn Off.
        /// </summary>
        internal static string Button_TurnOff {
            get {
                return ResourceManager.GetString("Button_TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;onnect....
        /// </summary>
        internal static string Command_Connect {
            get {
                return ResourceManager.GetString("Command_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause.
        /// </summary>
        internal static string Command_Pause {
            get {
                return ResourceManager.GetString("Command_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        internal static string Command_Reset {
            get {
                return ResourceManager.GetString("Command_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Res&amp;ume.
        /// </summary>
        internal static string Command_Resume {
            get {
                return ResourceManager.GetString("Command_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut Do&amp;wn....
        /// </summary>
        internal static string Command_ShutDown {
            get {
                return ResourceManager.GetString("Command_ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start.
        /// </summary>
        internal static string Command_Start {
            get {
                return ResourceManager.GetString("Command_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Turn Off....
        /// </summary>
        internal static string Command_TurnOff {
            get {
                return ResourceManager.GetString("Command_TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyper-V Manager.
        /// </summary>
        internal static string Menu_HyperVManager {
            get {
                return ResourceManager.GetString("Menu_HyperVManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset this virtual machine? If you reset this virtual machine, you will lose all unsaved changes..
        /// </summary>
        internal static string Message_ConfirmationReset {
            get {
                return ResourceManager.GetString("Message_ConfirmationReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the selected virtual machine(s)?.
        /// </summary>
        internal static string Message_ConfirmationResetMultiple {
            get {
                return ResourceManager.GetString("Message_ConfirmationResetMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to shut down the operating system in this virtual machine?.
        /// </summary>
        internal static string Message_ConfirmationShutDown {
            get {
                return ResourceManager.GetString("Message_ConfirmationShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to shut down the operating system in the selected virtual machine(s)?.
        /// </summary>
        internal static string Message_ConfirmationShutDownMultiple {
            get {
                return ResourceManager.GetString("Message_ConfirmationShutDownMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to turn off this virtual machine? This is equivalent to powering off a computer, so data loss is possible..
        /// </summary>
        internal static string Message_ConfirmationTurnOff {
            get {
                return ResourceManager.GetString("Message_ConfirmationTurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to turn off the selected virtual machine(s)? This is equivalent to powering off a computer, so data loss is possible..
        /// </summary>
        internal static string Message_ConfirmationTurnOffMultiple {
            get {
                return ResourceManager.GetString("Message_ConfirmationTurnOffMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to launch the Virtual Machine Connection application for the selected virtual machine..
        /// </summary>
        internal static string Message_OpenVMConnectFailed {
            get {
                return ResourceManager.GetString("Message_OpenVMConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to pause virtual machine {0}..
        /// </summary>
        internal static string Message_PauseVMFailed {
            get {
                return ResourceManager.GetString("Message_PauseVMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to pause the selected virtual machine(s)..
        /// </summary>
        internal static string Message_PauseVMFailedMultiple {
            get {
                return ResourceManager.GetString("Message_PauseVMFailedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to power off virtual machine {0}..
        /// </summary>
        internal static string Message_PowerOffVMFailed {
            get {
                return ResourceManager.GetString("Message_PowerOffVMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to turn off the selected virtual machine(s)..
        /// </summary>
        internal static string Message_PowerOffVMFailedMultiple {
            get {
                return ResourceManager.GetString("Message_PowerOffVMFailedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to reset virtual machine {0}..
        /// </summary>
        internal static string Message_ResetVMFailed {
            get {
                return ResourceManager.GetString("Message_ResetVMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to reset the selected virtual machine(s)..
        /// </summary>
        internal static string Message_ResetVMFailedMultiple {
            get {
                return ResourceManager.GetString("Message_ResetVMFailedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to resume the selected virtual machine(s)..
        /// </summary>
        internal static string Message_ResumeVMFailedMultiple {
            get {
                return ResourceManager.GetString("Message_ResumeVMFailedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to save the state of virtual machine {0}..
        /// </summary>
        internal static string Message_SaveStateVMFailed {
            get {
                return ResourceManager.GetString("Message_SaveStateVMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to save the state of the selected virtual machine(s)..
        /// </summary>
        internal static string Message_SaveStateVMFailedMultiple {
            get {
                return ResourceManager.GetString("Message_SaveStateVMFailedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to shut down the virtual machine(s)..
        /// </summary>
        internal static string Message_ShutDownVMFailedMultiple {
            get {
                return ResourceManager.GetString("Message_ShutDownVMFailedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to start virtual machine {0}..
        /// </summary>
        internal static string Message_StartVMFailed {
            get {
                return ResourceManager.GetString("Message_StartVMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to start the selected virtual machine(s)..
        /// </summary>
        internal static string Message_StartVMFailedMultiple {
            get {
                return ResourceManager.GetString("Message_StartVMFailedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxCritical.
        /// </summary>
        internal static string State_Critical {
            get {
                return ResourceManager.GetString("State_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxPaused.
        /// </summary>
        internal static string State_Paused {
            get {
                return ResourceManager.GetString("State_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxRunning.
        /// </summary>
        internal static string State_Running {
            get {
                return ResourceManager.GetString("State_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxSaved.
        /// </summary>
        internal static string State_Saved {
            get {
                return ResourceManager.GetString("State_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Machine.
        /// </summary>
        internal static string Title_ResetMachine {
            get {
                return ResourceManager.GetString("Title_ResetMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut Down Machine.
        /// </summary>
        internal static string Title_ShutDownMachine {
            get {
                return ResourceManager.GetString("Title_ShutDownMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off Machine.
        /// </summary>
        internal static string Title_TurnOffMachine {
            get {
                return ResourceManager.GetString("Title_TurnOffMachine", resourceCulture);
            }
        }
    }
}
