//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperVTray.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsFallback {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsFallback() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HyperVTray.Resources.StringsFallback", typeof(StringsFallback).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxC&amp;amp;onnect....
        /// </summary>
        internal static string Command_Connect {
            get {
                return ResourceManager.GetString("Command_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xx&amp;amp;Pause.
        /// </summary>
        internal static string Command_Pause {
            get {
                return ResourceManager.GetString("Command_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxPause All.
        /// </summary>
        internal static string Command_PauseAll {
            get {
                return ResourceManager.GetString("Command_PauseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xx&amp;amp;Reset.
        /// </summary>
        internal static string Command_Reset {
            get {
                return ResourceManager.GetString("Command_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxReset All.
        /// </summary>
        internal static string Command_ResetAll {
            get {
                return ResourceManager.GetString("Command_ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxRes&amp;amp;ume.
        /// </summary>
        internal static string Command_Resume {
            get {
                return ResourceManager.GetString("Command_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxResume All.
        /// </summary>
        internal static string Command_ResumeAll {
            get {
                return ResourceManager.GetString("Command_ResumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xx&amp;amp;Save.
        /// </summary>
        internal static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxSave All.
        /// </summary>
        internal static string Command_SaveAll {
            get {
                return ResourceManager.GetString("Command_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxShut Do&amp;amp;wn....
        /// </summary>
        internal static string Command_ShutDown {
            get {
                return ResourceManager.GetString("Command_ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxShutdown All.
        /// </summary>
        internal static string Command_ShutDownAll {
            get {
                return ResourceManager.GetString("Command_ShutDownAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xx&amp;amp;Start.
        /// </summary>
        internal static string Command_Start {
            get {
                return ResourceManager.GetString("Command_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxStart All.
        /// </summary>
        internal static string Command_StartAll {
            get {
                return ResourceManager.GetString("Command_StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xx&amp;amp;Turn Off....
        /// </summary>
        internal static string Command_TurnOff {
            get {
                return ResourceManager.GetString("Command_TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxTurn Off All.
        /// </summary>
        internal static string Command_TurnOffAll {
            get {
                return ResourceManager.GetString("Command_TurnOffAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxHyper-V Manager.
        /// </summary>
        internal static string Menu_HyperVManager {
            get {
                return ResourceManager.GetString("Menu_HyperVManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxAn error occurred while attempting to pause the selected virtual machine(s)..
        /// </summary>
        internal static string Message_PauseVMFailed {
            get {
                return ResourceManager.GetString("Message_PauseVMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxAn error occurred while attempting to turn off the selected virtual machine(s)..
        /// </summary>
        internal static string Message_PowerOffVMFailed {
            get {
                return ResourceManager.GetString("Message_PowerOffVMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxAn error occurred while attempting to reset the selected virtual machine(s)..
        /// </summary>
        internal static string Message_ResetVMFailed {
            get {
                return ResourceManager.GetString("Message_ResetVMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxAn error occurred while attempting to resume the selected virtual machine(s)..
        /// </summary>
        internal static string Message_ResumeVMFailed {
            get {
                return ResourceManager.GetString("Message_ResumeVMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxAn error occurred while attempting to save the state of the selected virtual machine(s)..
        /// </summary>
        internal static string Message_SaveStateVMFailed {
            get {
                return ResourceManager.GetString("Message_SaveStateVMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxAn error occurred while attempting to shut down the virtual machine(s)..
        /// </summary>
        internal static string Message_ShutDownVMFailed {
            get {
                return ResourceManager.GetString("Message_ShutDownVMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxAn error occurred while attempting to start the selected virtual machine(s)..
        /// </summary>
        internal static string Message_StartVMFailed {
            get {
                return ResourceManager.GetString("Message_StartVMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateCritical.
        /// </summary>
        internal static string State_Critical {
            get {
                return ResourceManager.GetString("State_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateOff.
        /// </summary>
        internal static string State_Off {
            get {
                return ResourceManager.GetString("State_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatePaused.
        /// </summary>
        internal static string State_Paused {
            get {
                return ResourceManager.GetString("State_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateRunning.
        /// </summary>
        internal static string State_Running {
            get {
                return ResourceManager.GetString("State_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateSaved.
        /// </summary>
        internal static string State_Saved {
            get {
                return ResourceManager.GetString("State_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Virtual Machine.
        /// </summary>
        internal static string String_UnknownVirtualMachine {
            get {
                return ResourceManager.GetString("String_UnknownVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine is in a critical state..
        /// </summary>
        internal static string Toast_CriticalState {
            get {
                return ResourceManager.GetString("Toast_CriticalState", resourceCulture);
            }
        }
    }
}
